/* This file is generated by tools/genexports.ts - DO NOT EDIT */

import jsc from '../jsc.js';

export default jsc;

export const { setTimeZone } = jsc;
export const { profile } = jsc;
export const { startSamplingProfiler } = jsc;
export const { callerSourceOrigin } = jsc;
export const { jscDescribe } = jsc;
export const { jscDescribeArray } = jsc;
export const { drainMicrotasks } = jsc;
export const { edenGC } = jsc;
export const { fullGC } = jsc;
export const { gcAndSweep } = jsc;
export const { getProtectedObjects } = jsc;
export const { getRandomSeed } = jsc;
export const { heapSize } = jsc;
export const { heapStats } = jsc;
export const { isRope } = jsc;
export const { memoryUsage } = jsc;
export const { noFTL } = jsc;
export const { noOSRExitFuzzing } = jsc;
export const { numberOfDFGCompiles } = jsc;
export const { optimizeNextInvocation } = jsc;
export const { releaseWeakRefs } = jsc;
export const { reoptimizationRetryCount } = jsc;
export const { setRandomSeed } = jsc;
export const { startRemoteDebugger } = jsc;
export const { totalCompileTime } = jsc;
